version: "3.8"

services:
  backend:
    build: ./server
    container_name: shortly_backend
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    # Убрали depends_on: mongo, так как база внешняя

  frontend:
    build: .
    container_name: shortly_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
